# 基础镜像
FROM openjdk:8-jre-slim
# 作者
MAINTAINER 水门土一
# 配置
ENV PARAMS=""
# 时区
ENV TZ=PRC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 添加应用
ADD /gptbot-interfaces/target/gptbot-api.jar /gptbot-api.jar
# 执行镜像；docker run -e PARAMS=" --gptbot-api.groupId=你的星球ID --gptbot-api.openAiKey=自行申请 --gptbot-api.cookie=登录cookie信息" -p 8090:8090 --name gptbot-api -d gptbot-api:1.0
ENTRYPOINT ["sh","-c","java -jar $JAVA_OPTS /gptbot-api.jar $PARAMS"]